name: Run cfstfd

on:
  schedule:
    # 使用 cron 语法设置定时任务 (UTC 时间)
    - cron: '0 */6 * * *'  # 每隔6小时在0分钟执行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  run-autoddns:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 确保有权限推送代码

    env:
      # 设置环境变量，使用 GitHub Secrets
      CLOUDFLARE_API_KEY: ${{ secrets.CLOUDFLARE_API_KEY }}
      CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
      CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run cfstfd script
      run: |
        python cfstfd.py

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        if git diff --quiet; then
          echo "No changes to commit."
        else
          git add .
          git commit -m "cfst: Auto-update fd.txt $(date +'%Y-%m-%d %H:%M')"
          git push origin main
        fi