name: Run autoddnsfd

on:
  push:
    branches:
      - main  # 仅在推送到 main 分支时触发，可以修改为你想要的分支
    paths:
      - 'cfip/fd.txt'  # 只有 fd.txt 文件发生变化时才触发

jobs:
  run-autoddns:
    runs-on: ubuntu-latest

    env:
      # 设置环境变量，使用 GitHub Secrets
      CLOUDFLARE_API_KEY: ${{ secrets.CLOUDFLARE_API_KEY }}
      CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
      CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run autoddnsfd script
      run: |
        python ddns/autoddnsfd.py